"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Player = { id: string; name: string; score: number };
type Chat = { sender: string; message: string; system: boolean };
type GameState = { room: string; hostId: string; you: string; category: string; categories: string[]; round: number; solved: boolean; hintLevel?: number; players: Player[]; messages: Chat[]; imageUrl?: string; questionCategory?: string; answer?: string };
const initial: GameState = { room: "", hostId: "", you: "", category: "전체", categories: ["전체", "연예인"], round: 0, solved: false, players: [], messages: [] };
const api = () => process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") ?? (location.hostname === "localhost" ? "http://localhost:8080" : "https://wax-cracking-backend.onrender.com");
const newCode = () => Array.from({ length: 6 }, () => "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random() * 32)]).join("");

export default function PeopleQuiz() {
  const [room, setRoom] = useState(""); const [draft, setDraft] = useState(""); const [name, setName] = useState(""); const [state, setState] = useState(initial); const [message, setMessage] = useState(""); const [connected, setConnected] = useState(false); const [dark, setDark] = useState(true); const ws = useRef<WebSocket | null>(null);
  const isHost = state.you === state.hostId; const players = useMemo(() => [...state.players].sort((a, b) => b.score - a.score), [state.players]);
  useEffect(() => { const saved = localStorage.getItem("people-quiz-theme"); if (saved) setDark(saved === "dark"); }, []);
  useEffect(() => { localStorage.setItem("people-quiz-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { if (!room) return; const socket = new WebSocket(api().replace(/^http/, "ws") + `/ws/people-quiz?room=${room}`); ws.current = socket; socket.onopen = () => { setConnected(true); socket.send(JSON.stringify({ type: "profile", nickname: name || "플레이어" })); }; socket.onclose = () => setConnected(false); socket.onmessage = (event) => { const next = JSON.parse(event.data); if (next.type === "state") setState(next); }; return () => socket.close(); }, [room, name]);
  const send = (type: string, extra = {}) => ws.current?.readyState === WebSocket.OPEN && ws.current.send(JSON.stringify({ type, ...extra }));
  const join = (value: string) => { const normalized = value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 12); if (normalized) { setDraft(normalized); setRoom(normalized); setState(initial); } };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; send(state.imageUrl && !state.solved ? "guess" : "chat", { message }); setMessage(""); };
  const surface = dark ? "border-white/10 bg-[#11182a]" : "border-slate-200 bg-white shadow-sm"; const soft = dark ? "bg-white/5 text-slate-300" : "bg-slate-100 text-slate-700"; const text = dark ? "text-white" : "text-slate-900"; const muted = dark ? "text-slate-400" : "text-slate-500";
  return <main className={`min-h-screen transition-colors ${dark ? "bg-[#090d1a]" : "bg-[#f6f7fb]"} ${text}`}><div className="mx-auto w-[min(1180px,calc(100%-32px))] py-7">
    <nav className="mb-8 flex items-center justify-between"><Link href="/" className={`text-sm font-bold ${muted}`}>홈으로</Link><div className="flex items-center gap-3"><div className={`flex items-center gap-2 text-xs font-bold ${muted}`}><i className={`h-2 w-2 rounded-full ${connected ? "bg-emerald-400" : "bg-slate-400"}`}/>{connected ? "실시간 연결됨" : "오프라인"}</div><button onClick={() => setDark((value) => !value)} className={`rounded-xl border px-3 py-2 text-xs font-black ${dark ? "border-white/15 bg-white/10" : "border-slate-200 bg-white"}`}>{dark ? "☀ 라이트 모드" : "☾ 다크 모드"}</button></div></nav>
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-black tracking-[.3em] text-[#c99012]">실시간 인물 퀴즈</p><h1 className="text-4xl font-black sm:text-5xl">누구일까요?</h1></div><div className={`rounded-2xl border px-5 py-3 text-sm ${surface}`}><span className={muted}>방 코드 </span><b className="ml-2 tracking-[.2em]">{room || "------"}</b></div></header>
    {!room ? <section className={`grid gap-5 rounded-3xl border p-8 md:grid-cols-[1fr_auto] ${surface}`}><div><h2 className="text-2xl font-black">친구들과 퀴즈를 시작하세요.</h2><p className={`mt-2 ${muted}`}>방을 만들고 코드를 공유한 뒤, 사진 속 인물을 가장 먼저 맞혀보세요.</p><input value={name} onChange={(e) => setName(e.target.value)} placeholder="닉네임" maxLength={16} className={`mt-6 w-full max-w-md rounded-xl border px-4 py-3 font-bold outline-none ${dark ? "border-white/10 bg-[#090d1a]" : "border-slate-200 bg-slate-50"}`}/></div><div className="flex flex-col justify-center gap-2"><button onClick={() => join(newCode())} className="rounded-xl bg-[#f8c94e] px-6 py-3 font-black text-[#14110a]">방 만들기</button><div className="flex gap-2"><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="방 코드" className={`w-32 rounded-xl border px-3 py-2 text-sm font-bold ${dark ? "border-white/10 bg-[#090d1a]" : "border-slate-200 bg-slate-50"}`}/><button onClick={() => join(draft)} className={`rounded-xl border px-4 text-sm font-bold ${dark ? "border-white/20" : "border-slate-300"}`}>입장</button></div></div></section> : <section className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)_280px]">
      <aside className="order-2 space-y-4 lg:order-1"><div className={`rounded-2xl border p-4 ${surface}`}><p className={`text-xs font-black tracking-widest ${muted}`}>점수판</p><div className="mt-3 space-y-2">{players.map((player, index) => <div key={player.id} className={`flex items-center justify-between rounded-xl px-3 py-2 ${soft}`}><span className="font-bold"><b className="mr-2 text-[#c99012]">{index + 1}</b>{player.name}</span><b>{player.score}점</b></div>)}</div></div><div className={`rounded-2xl border p-4 ${surface}`}><p className={`text-xs font-black tracking-widest ${muted}`}>카테고리</p><div className="mt-3 flex flex-wrap gap-2">{state.categories.map((category) => <button disabled={!isHost} onClick={() => send("category", { category })} key={category} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${state.category === category ? "bg-[#f8c94e] text-black" : soft}`}>{category}</button>)}</div></div></aside>
      <div className={`order-1 overflow-hidden rounded-3xl border lg:order-2 ${surface}`}><div className="flex items-center justify-between border-b border-inherit px-5 py-4"><span className="text-xs font-black tracking-[.15em] text-[#c99012]">{state.imageUrl ? `${state.questionCategory} · ${state.round}번째 문제` : "게임 시작 대기 중"}</span>{isHost && <div className="flex gap-2"><button onClick={() => send("hint")} disabled={!state.imageUrl || state.solved} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${soft}`}>힌트 {state.hintLevel ? `(${state.hintLevel}/2)` : ""}</button><button onClick={() => send(state.imageUrl ? "next" : "start")} className="rounded-lg bg-[#f8c94e] px-3 py-1.5 text-xs font-black text-black">{state.imageUrl ? "다음 문제" : "게임 시작"}</button></div>}</div><div className="relative aspect-[4/3] bg-[#070a12]">{state.imageUrl ? <img src={state.imageUrl} alt="퀴즈 인물 사진" className={`h-full w-full object-cover transition duration-700 ${state.solved ? "blur-0 grayscale-0" : state.hintLevel === 2 ? "blur-[2px] grayscale-[.35]" : state.hintLevel === 1 ? "blur-[4px] grayscale-[.65]" : "blur-[7px] grayscale"}`}/> : <div className="flex h-full flex-col items-center justify-center text-center text-slate-400"><span className="text-7xl">?</span><p className="mt-4 font-bold">호스트가 첫 문제를 시작합니다</p></div>}{state.solved && <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 p-7 text-center text-white"><p className="text-xs font-black tracking-[.25em] text-[#f8c94e]">정답</p><h2 className="mt-1 text-3xl font-black">{state.answer}</h2><p className="mt-2 text-sm text-slate-300">2초 뒤 다음 문제로 넘어갑니다.</p></div>}</div><form onSubmit={submit} className="flex gap-2 border-t border-inherit p-4"><input disabled={!state.imageUrl || state.solved} value={message} onChange={(e) => setMessage(e.target.value)} placeholder={state.imageUrl && !state.solved ? "정답을 입력하세요" : "채팅을 입력하세요"} className={`min-w-0 flex-1 rounded-xl px-4 py-3 font-medium outline-none disabled:opacity-50 ${dark ? "bg-white/5" : "bg-slate-100"}`}/><button className="rounded-xl bg-[#f8c94e] px-5 font-black text-[#111827] disabled:opacity-40" disabled={!message.trim()}>전송</button></form></div>
      <aside className={`order-3 rounded-2xl border p-4 ${surface}`}><p className={`text-xs font-black tracking-widest ${muted}`}>실시간 채팅</p><div className="mt-3 h-[300px] space-y-3 overflow-y-auto pr-1">{state.messages.map((chat, index) => <div key={index} className={`text-sm ${chat.system ? "rounded-xl bg-[#f8c94e]/15 p-3 text-[#a16a00]" : ""}`}><b className="mr-2">{chat.sender}</b><span className={dark ? "text-slate-300" : "text-slate-600"}>{chat.message}</span></div>)}</div></aside>
    </section>}</div></main>;
}
