"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Player={id:string;name:string;score:number}; type Chat={sender:string;message:string;system:boolean};
type State={room:string;hostId:string;you:string;category:string;categories:string[];round:number;solved:boolean;players:Player[];messages:Chat[];imageUrl?:string;questionCategory?:string;answer?:string};
const initial:State={room:"",hostId:"",you:"",category:"전체",categories:["전체","과학","리더","예술"],round:0,solved:false,players:[],messages:[]};
const api=()=>{const env=process.env.NEXT_PUBLIC_API_BASE_URL;if(env)return env.replace(/\/$/,"");return location.hostname==="localhost"?"http://localhost:8080":"https://wax-cracking-backend.onrender.com"};
const code=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("");
export default function PeopleQuiz(){
 const [room,setRoom]=useState("");const [draft,setDraft]=useState("");const [name,setName]=useState("");const [state,setState]=useState(initial);const [message,setMessage]=useState("");const [connected,setConnected]=useState(false);const ws=useRef<WebSocket|null>(null);const isHost=state.you===state.hostId;
 useEffect(()=>{if(!room)return;const socket=new WebSocket(api().replace(/^http/,"ws")+`/ws/people-quiz?room=${room}`);ws.current=socket;socket.onopen=()=>{setConnected(true);socket.send(JSON.stringify({type:"profile",nickname:name||"플레이어"}));};socket.onclose=()=>setConnected(false);socket.onmessage=e=>{const v=JSON.parse(e.data);if(v.type==="state")setState(v)};return()=>socket.close()},[room,name]);
 const send=(type:string,extra={})=>ws.current?.readyState===WebSocket.OPEN&&ws.current.send(JSON.stringify({type,...extra}));
 const join=(r:string)=>{const normalized=r.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,12);if(normalized){setDraft(normalized);setRoom(normalized);setState(initial)}};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!message.trim())return;send(state.imageUrl&&!state.solved?"guess":"chat",{message});setMessage("")};const sorted=useMemo(()=>[...state.players].sort((a,b)=>b.score-a.score),[state.players]);
 return <main className="min-h-screen bg-[#090d1a] text-white selection:bg-[#f8c94e] selection:text-[#090d1a]"><div className="mx-auto w-[min(1180px,calc(100%-32px))] py-7">
  <nav className="mb-8 flex items-center justify-between"><Link href="/" className="text-sm font-bold text-slate-300 hover:text-white">홈으로</Link><div className="flex items-center gap-2 text-xs font-bold tracking-[.18em]"><i className={`h-2 w-2 rounded-full ${connected?"bg-emerald-400":"bg-slate-600"}`}/>{connected?"실시간 연결됨":"오프라인"}</div></nav>
  <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-black tracking-[.3em] text-[#f8c94e]">실시간 인물 퀴즈</p><h1 className="text-4xl font-black tracking-tight sm:text-5xl">누구일까요?<span className="text-[#f8c94e]"> LIVE</span></h1></div><div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-sm"><span className="text-slate-400">방 코드 </span><b className="ml-2 tracking-[.2em]">{room||"------"}</b></div></header>
  {!room?<section className="grid gap-5 rounded-3xl border border-white/10 bg-[#11182a] p-8 md:grid-cols-[1fr_auto]"><div><h2 className="text-2xl font-black">친구들과 퀴즈를 시작하세요.</h2><p className="mt-2 text-slate-400">방을 만들고 코드를 공유한 뒤, 사진 속 인물을 가장 먼저 맞혀보세요.</p><div className="mt-6 flex max-w-md gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="닉네임" maxLength={16} className="w-full rounded-xl border border-white/10 bg-[#090d1a] px-4 py-3 font-bold outline-none focus:border-[#f8c94e]"/></div></div><div className="flex flex-col justify-center gap-2"><button onClick={()=>join(code())} className="rounded-xl bg-[#f8c94e] px-6 py-3 font-black text-[#14110a] hover:bg-[#ffdb72]">방 만들기</button><div className="flex gap-2"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="방 코드" className="w-32 rounded-xl border border-white/10 bg-[#090d1a] px-3 py-2 text-sm font-bold outline-none"/><button onClick={()=>join(draft)} className="rounded-xl border border-white/20 px-4 text-sm font-bold">입장</button></div></div></section>:<section className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)_280px]">
   <aside className="order-2 space-y-4 lg:order-1"><div className="rounded-2xl border border-white/10 bg-[#11182a] p-4"><p className="text-xs font-black tracking-widest text-slate-400">점수판</p><div className="mt-3 space-y-2">{sorted.map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-xl bg-white/5 px-3 py-2"><span className="font-bold"><b className="mr-2 text-[#f8c94e]">{i+1}</b>{p.name}</span><b>{p.score}점</b></div>)}</div></div><div className="rounded-2xl border border-white/10 bg-[#11182a] p-4"><p className="text-xs font-black tracking-widest text-slate-400">카테고리</p><div className="mt-3 flex flex-wrap gap-2">{state.categories.map(c=><button disabled={!isHost} onClick={()=>send("category",{category:c})} key={c} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${state.category===c?"bg-[#f8c94e] text-black":"bg-white/5 text-slate-300"}`}>{c}</button>)}</div></div></aside>
   <div className="order-1 overflow-hidden rounded-3xl border border-white/10 bg-[#11182a] lg:order-2"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><span className="text-xs font-black tracking-[.2em] text-[#f8c94e]">{state.imageUrl?`${state.questionCategory} · ${state.round}번째 문제`:"게임 시작 대기 중"}</span>{isHost&&<div className="flex gap-2"><button onClick={()=>send("hint")} disabled={!state.imageUrl} className="rounded-lg bg-white/10 px-3 py-1.5 text-xs font-bold">힌트</button><button onClick={()=>send(state.imageUrl?"next":"start")} className="rounded-lg bg-[#f8c94e] px-3 py-1.5 text-xs font-black text-black">{state.imageUrl?"다음 문제":"게임 시작"}</button></div>}</div><div className="relative aspect-[4/3] bg-[#070a12]">{state.imageUrl?<img src={state.imageUrl} alt="퀴즈 인물 사진" className={`h-full w-full object-cover transition duration-700 ${state.solved?"blur-0 grayscale-0":"blur-[7px] grayscale"}`}/>:<div className="flex h-full flex-col items-center justify-center text-center"><span className="text-7xl">?</span><p className="mt-4 font-bold text-slate-400">호스트가 첫 문제를 시작합니다</p></div>}{state.solved&&<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 p-7 text-center"><p className="text-xs font-black tracking-[.25em] text-[#f8c94e]">정답</p><h2 className="mt-1 text-3xl font-black">{state.answer}</h2></div>}</div><form onSubmit={submit} className="flex gap-2 border-t border-white/10 p-4"><input disabled={!state.imageUrl||state.solved} value={message} onChange={e=>setMessage(e.target.value)} placeholder={state.imageUrl&&!state.solved?"정답을 입력하세요":"채팅을 입력하세요"} className="min-w-0 flex-1 rounded-xl bg-white/5 px-4 py-3 font-medium outline-none focus:ring-2 focus:ring-[#f8c94e] disabled:opacity-50"/><button className="rounded-xl bg-white px-5 font-black text-[#111827] disabled:opacity-40" disabled={!message.trim()}>전송</button></form></div>
   <aside className="order-3 rounded-2xl border border-white/10 bg-[#11182a] p-4"><p className="text-xs font-black tracking-widest text-slate-400">실시간 채팅</p><div className="mt-3 h-[300px] space-y-3 overflow-y-auto pr-1">{state.messages.map((m,i)=><div key={i} className={`text-sm ${m.system?"rounded-xl bg-[#f8c94e]/10 p-3 text-[#f8d87b]":""}`}><b className="mr-2">{m.sender}</b><span className="text-slate-300">{m.message}</span></div>)}</div></aside>
  </section>}</div></main>
}
